# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sidebar.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sidebar(object):
    def setupUi(self, Sidebar):
        Sidebar.setObjectName("Sidebar")
        Sidebar.resize(430, 940)
        self.gridLayout_15 = QtWidgets.QGridLayout(Sidebar)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.tabWidget = QtWidgets.QTabWidget(Sidebar)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.load_images_groupbox = QtWidgets.QGroupBox(self.tab)
        self.load_images_groupbox.setObjectName("load_images_groupbox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.load_images_groupbox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.images_dir_line_edit = QtWidgets.QLineEdit(self.load_images_groupbox)
        self.images_dir_line_edit.setReadOnly(True)
        self.images_dir_line_edit.setObjectName("images_dir_line_edit")
        self.horizontalLayout.addWidget(self.images_dir_line_edit)
        self.image_loaded_checkbox = QtWidgets.QCheckBox(self.load_images_groupbox)
        self.image_loaded_checkbox.setEnabled(False)
        self.image_loaded_checkbox.setText("")
        self.image_loaded_checkbox.setCheckable(True)
        self.image_loaded_checkbox.setObjectName("image_loaded_checkbox")
        self.horizontalLayout.addWidget(self.image_loaded_checkbox)
        self.load_images = QtWidgets.QToolButton(self.load_images_groupbox)
        self.load_images.setObjectName("load_images")
        self.horizontalLayout.addWidget(self.load_images)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.load_images_groupbox, 0, 0, 1, 1)
        self.load_trajectory_groupbox = QtWidgets.QGroupBox(self.tab)
        self.load_trajectory_groupbox.setObjectName("load_trajectory_groupbox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.load_trajectory_groupbox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lidar_trajectory_path_line_edit = QtWidgets.QLineEdit(self.load_trajectory_groupbox)
        self.lidar_trajectory_path_line_edit.setReadOnly(True)
        self.lidar_trajectory_path_line_edit.setObjectName("lidar_trajectory_path_line_edit")
        self.horizontalLayout_2.addWidget(self.lidar_trajectory_path_line_edit)
        self.lidar_trajectory_loaded_checkbox = QtWidgets.QCheckBox(self.load_trajectory_groupbox)
        self.lidar_trajectory_loaded_checkbox.setEnabled(False)
        self.lidar_trajectory_loaded_checkbox.setText("")
        self.lidar_trajectory_loaded_checkbox.setCheckable(True)
        self.lidar_trajectory_loaded_checkbox.setObjectName("lidar_trajectory_loaded_checkbox")
        self.horizontalLayout_2.addWidget(self.lidar_trajectory_loaded_checkbox)
        self.load_lidar_trajectory = QtWidgets.QToolButton(self.load_trajectory_groupbox)
        self.load_lidar_trajectory.setObjectName("load_lidar_trajectory")
        self.horizontalLayout_2.addWidget(self.load_lidar_trajectory)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.gridLayout_7.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.load_trajectory_groupbox, 1, 0, 1, 1)
        self.load_vector_map_groupbox = QtWidgets.QGroupBox(self.tab)
        self.load_vector_map_groupbox.setObjectName("load_vector_map_groupbox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.load_vector_map_groupbox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.vector_map_path_line_edit = QtWidgets.QLineEdit(self.load_vector_map_groupbox)
        self.vector_map_path_line_edit.setReadOnly(True)
        self.vector_map_path_line_edit.setObjectName("vector_map_path_line_edit")
        self.horizontalLayout_4.addWidget(self.vector_map_path_line_edit)
        self.vector_map_loaded_checkbox = QtWidgets.QCheckBox(self.load_vector_map_groupbox)
        self.vector_map_loaded_checkbox.setEnabled(False)
        self.vector_map_loaded_checkbox.setText("")
        self.vector_map_loaded_checkbox.setCheckable(True)
        self.vector_map_loaded_checkbox.setObjectName("vector_map_loaded_checkbox")
        self.horizontalLayout_4.addWidget(self.vector_map_loaded_checkbox)
        self.load_vector_map = QtWidgets.QToolButton(self.load_vector_map_groupbox)
        self.load_vector_map.setObjectName("load_vector_map")
        self.horizontalLayout_4.addWidget(self.load_vector_map)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.show_vector_map_checkbox = QtWidgets.QCheckBox(self.load_vector_map_groupbox)
        self.show_vector_map_checkbox.setObjectName("show_vector_map_checkbox")
        self.horizontalLayout_7.addWidget(self.show_vector_map_checkbox)
        self.reprojection_vector_map_btn = QtWidgets.QPushButton(self.load_vector_map_groupbox)
        self.reprojection_vector_map_btn.setObjectName("reprojection_vector_map_btn")
        self.horizontalLayout_7.addWidget(self.reprojection_vector_map_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.load_vector_map_groupbox, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_15.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(Sidebar)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.add_correspondence_btn = QtWidgets.QToolButton(self.groupBox_6)
        self.add_correspondence_btn.setObjectName("add_correspondence_btn")
        self.horizontalLayout_5.addWidget(self.add_correspondence_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.clear_correspondences_btn = QtWidgets.QToolButton(self.groupBox_6)
        self.clear_correspondences_btn.setObjectName("clear_correspondences_btn")
        self.horizontalLayout_5.addWidget(self.clear_correspondences_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.correspondence_path_line_edit = QtWidgets.QLineEdit(self.groupBox_6)
        self.correspondence_path_line_edit.setReadOnly(True)
        self.correspondence_path_line_edit.setObjectName("correspondence_path_line_edit")
        self.horizontalLayout_9.addWidget(self.correspondence_path_line_edit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.load_correspondences_btn = QtWidgets.QToolButton(self.groupBox_6)
        self.load_correspondences_btn.setObjectName("load_correspondences_btn")
        self.horizontalLayout_11.addWidget(self.load_correspondences_btn)
        self.save_correspondences_btn = QtWidgets.QToolButton(self.groupBox_6)
        self.save_correspondences_btn.setObjectName("save_correspondences_btn")
        self.horizontalLayout_11.addWidget(self.save_correspondences_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.show_correspondences_checkbox = QtWidgets.QCheckBox(self.groupBox_6)
        self.show_correspondences_checkbox.setObjectName("show_correspondences_checkbox")
        self.horizontalLayout_12.addWidget(self.show_correspondences_checkbox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.darken_image_background_checkbox = QtWidgets.QCheckBox(self.groupBox_6)
        self.darken_image_background_checkbox.setObjectName("darken_image_background_checkbox")
        self.horizontalLayout_13.addWidget(self.darken_image_background_checkbox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.gridLayout_8.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.toggle_optimization_checkbox = QtWidgets.QCheckBox(self.groupBox_7)
        self.toggle_optimization_checkbox.setObjectName("toggle_optimization_checkbox")
        self.horizontalLayout_3.addWidget(self.toggle_optimization_checkbox)
        self.execute_optimize_btn = QtWidgets.QToolButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.execute_optimize_btn.sizePolicy().hasHeightForWidth())
        self.execute_optimize_btn.setSizePolicy(sizePolicy)
        self.execute_optimize_btn.setObjectName("execute_optimize_btn")
        self.horizontalLayout_3.addWidget(self.execute_optimize_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.gridLayout_10.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.gridLayout_15.addWidget(self.tabWidget_2, 2, 0, 1, 1)
        self.tabWidget_3 = QtWidgets.QTabWidget(Sidebar)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.prev_image_btn = QtWidgets.QToolButton(self.tab_3)
        self.prev_image_btn.setObjectName("prev_image_btn")
        self.horizontalLayout_6.addWidget(self.prev_image_btn)
        self.image_index_label = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.image_index_label.setFont(font)
        self.image_index_label.setTextFormat(QtCore.Qt.PlainText)
        self.image_index_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_index_label.setObjectName("image_index_label")
        self.horizontalLayout_6.addWidget(self.image_index_label)
        self.next_image_btn = QtWidgets.QToolButton(self.tab_3)
        self.next_image_btn.setObjectName("next_image_btn")
        self.horizontalLayout_6.addWidget(self.next_image_btn)
        self.gridLayout_11.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_3, "")
        self.gridLayout_15.addWidget(self.tabWidget_3, 3, 0, 1, 1)

        self.retranslateUi(Sidebar)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Sidebar)

    def retranslateUi(self, Sidebar):
        _translate = QtCore.QCoreApplication.translate
        Sidebar.setWindowTitle(_translate("Sidebar", "Sidebar"))
        self.load_images_groupbox.setTitle(_translate("Sidebar", "Load Images"))
        self.load_images.setText(_translate("Sidebar", "..."))
        self.load_trajectory_groupbox.setTitle(_translate("Sidebar", "Load Lidar trajectory"))
        self.load_lidar_trajectory.setText(_translate("Sidebar", "..."))
        self.load_vector_map_groupbox.setTitle(_translate("Sidebar", "Load Vector Map"))
        self.load_vector_map.setText(_translate("Sidebar", "..."))
        self.show_vector_map_checkbox.setText(_translate("Sidebar", "Show vector map"))
        self.reprojection_vector_map_btn.setText(_translate("Sidebar", "refresh reprojection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Sidebar", "Load"))
        self.groupBox_6.setTitle(_translate("Sidebar", "Edit Correspondences"))
        self.add_correspondence_btn.setText(_translate("Sidebar", "Add correspondence"))
        self.clear_correspondences_btn.setText(_translate("Sidebar", "Clear correspondences"))
        self.load_correspondences_btn.setText(_translate("Sidebar", "Load correspondences"))
        self.save_correspondences_btn.setText(_translate("Sidebar", "Save correspondences"))
        self.show_correspondences_checkbox.setText(_translate("Sidebar", "Show correspondences"))
        self.darken_image_background_checkbox.setText(_translate("Sidebar", "Darken image background"))
        self.groupBox_7.setTitle(_translate("Sidebar", "Execute optimization"))
        self.toggle_optimization_checkbox.setText(_translate("Sidebar", "Toggle before/after optimization"))
        self.execute_optimize_btn.setText(_translate("Sidebar", "Optimize"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("Sidebar", "Calibration"))
        self.prev_image_btn.setText(_translate("Sidebar", "Prev Image"))
        self.image_index_label.setText(_translate("Sidebar", "0 / 0"))
        self.next_image_btn.setText(_translate("Sidebar", "Next Image"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_3), _translate("Sidebar", "Navigation"))


